{% set name = "phelel" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8bf30facf9ee02128662b3cb271a5765878b1f06dcca40f8b688d44d574bb5a

build:
  entry_points:
    - phelel = phelel.scripts.phelel:run
    - phelel-load = phelel.scripts.phelel_load:run
    - velph = phelel.velph.cli:cmd_root
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - phonopy >=2.33.4
    - phono3py >=3.6.0
    - finufft
    - click
    - tomli
    - tomli-w

test:
  imports:
    - phelel
  source_files:
    - test
  commands:
    - pip check
    - phelel --help
    - phelel-load --help
    - velph --help
    - pytest
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://github.com/phonopy/phelel
  description: |
    A code that provides a few computations needed to electron-phonon
    interaction calculation in finite-displacement method.
  summary: Finite-displacement electron-phonon code.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atztogo
