{% set name = "phelel" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/phelel-{{ version }}.tar.gz
  sha256: 075f1ae0621c69f327c6739e3759e681735135af69f57b965376552a6907afa2

build:
  entry_points:
    - phelel = phelel.scripts.phelel:run
    - phelel-load = phelel.scripts.phelel_load:run
    - velph = phelel.velph.cli:cmd_root
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - phono3py >=3.6.0
    - finufft
    - click
    - tomli
    - tomli-w

test:
  imports:
    - phelel
  source_files:
    - test
  commands:
    - pip check
    - phelel --help
    - phelel-load --help
    - velph --help
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/phonopy/phelel
  description: |
    A code that provides a few computations needed to electron-phonon
    interaction calculation in finite-displacement method.
  summary: Finite-displacement electron-phonon code.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atztogo
